Fix WebUI API doesn't update IP and Port
RetroShare/RetroShare pull request #1014
Opened 2017-09-05 04:53 UTC by myfingerhurt

Add a checker which prevents of adding your own gpg_id.
Add an inactive friends list based on last seen Unix timestamp.
Add a method of removing a specific peer based on peer_id.

2017-09-05 19:01 UTC, csoler commented
what do you mean by "not adding your own PGP Id" ? You should be able to add yourself as a friend when you have multiple locations.

2017-09-06 00:40 UTC, myfingerhurt commented
As fas as I know, the same pgp_id will discorvery themself and add online subnodes automaticlly even you remove one of them their just keep coming back, but if you accidently add your own peer_id on the WebUI, the peer list will show two identical PGP names and its subnodes, untill the retroshare gets restarted.  

And this modification don't add the same peer_id as long as it belongs to your current node, it doesn't mean you can't add your new nodes with the same pgp_id but different peer_id.

2017-09-12 04:08 UTC, G10h4ck requested changes
Nice work, please do some changes as per comments so we can integrate it into the code easly

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +void PeersHandler::handleRemoveNode(Request &req, Response &resp)
Don't like this approach, the function should work with location or with PGP id only, having so different behaviour depending on how parameters are passed is confusing, more over there is already another way to remove a PGP friend via API and it's 

/peers/${PGP_ID}/delete

So in my opinion this function should be for location only

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +void PeersHandler::handleGetInactiveUsers(Request &req, Response &resp)
As the API is used as a gateway to other languages too that may have different way of representing the date the representation format should be specified in the documentation

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +			do{
please use Allman indent style as per http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +				}else{
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +				if (!peerDetails.location.empty()) {
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +					if (!peerDetails.dyndns.empty()) {
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +	if(!gpgId.isNull()){
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +	}else if(!peerId.isNull()){
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +	}else{
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +	if(datetime.empty()){
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +		if(mapRsPgpId.find(details.gpg_id) != mapRsPgpId.end()){
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 04:08 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +		}else{
Please use Allman indent style http://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style

2017-09-12 07:09 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +void PeersHandler::handleRemoveNode(Request &req, Response &resp)
I'm trying to replace the `/peers/${PGP_ID}/delete` eventually.
And both removing `pgp_id` and removing `peer_id` are so similar, I think of putting them together may be more simplified.

2017-09-12 07:15 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +void PeersHandler::handleGetInactiveUsers(Request &req, Response &resp)
Add Unix Time notes.

2017-09-12 07:16 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +	if(datetime.empty()){
Done.

2017-09-12 07:17 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +	}else{
Done.

2017-09-12 07:17 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +		if(mapRsPgpId.find(details.gpg_id) != mapRsPgpId.end()){
Done.

2017-09-12 07:18 UTC, G10h4ck commented
Plese just drop the unwanted commits, not revert them to avoid history bloating as this isn't in master branch yet history rewriting is not a problem

2017-09-12 07:18 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +		}else{
Done.

2017-09-12 07:18 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +	}else if(!peerId.isNull()){
Done.

2017-09-12 07:19 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +	if(!gpgId.isNull()){
Done.

2017-09-12 07:19 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +					if (!peerDetails.dyndns.empty()) {
Done.

2017-09-12 07:19 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +				if (!peerDetails.location.empty()) {
Done.

2017-09-12 07:19 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +				}else{
Done.

2017-09-12 07:19 UTC, myfingerhurt commented on libresapi/src/api/PeersHandler.cpp
> +			do{
Done.

2017-09-12 08:12 UTC, myfingerhurt commented
I did what you had suggested.  Does it look good or worse?
```
git reset --hard xxxxxxxxxxxxxxxxx
git push -f
```

2017-09-12 08:27 UTC, G10h4ck commented on libresapi/src/api/PeersHandler.cpp
> +void PeersHandler::handleRemoveNode(Request &req, Response &resp)
Please do that ;)

2017-09-12 08:27 UTC, G10h4ck commented
Ok now please fix the Allman style thing ;)

2017-09-12 09:31 UTC, myfingerhurt commented
Well, I believe I have fixed Allman style things with my last commit.
Is there anything I haven't done? I'm trying to make git to ignore leading spaces and tabs or generate a patch file without indentation, it seems none exists.

2017-09-12 11:14 UTC, G10h4ck commented
The indentation fixes commit is not included in the PR probably it got caught in the revert/reset crossfire, you can cherry pick it probably and push again (no need for -f this time)

2017-09-15 07:34 UTC, merged

2017-09-15 07:36 UTC, G10h4ck commented
I have done the required modifications and merged it afterwards, thanks you for the contribution, please in the future use the qtcreator coding style file provided in the documentation so it is easier to merge your code ;)