V0.6 tor only
RetroShare/RetroShare pull request #1153
Opened 2018-01-17 23:10 UTC by csoler

This PR adds an option to RS to build a Tor version of RS which runs and configures Tor automatically at start. The running RS will only accept/create hidden nodes. GUI has been modified to not run/display unnecessary components such as DHT, IP filters, udp, etc.

To compile:
> qmake CONFIG="retrotor debug"
> make

To run:
- make sure you have a Tor executable in $path
- run RS normally.

Bridges are not supported yet, so if your ISP forbids Tor usage, RS-Tor will not start.

2018-01-18 21:40 UTC, hunbernd commented on retroshare-gui/src/TorControl/TorControl.cpp
> +
#include <time.h>

2018-01-19 19:24 UTC, G10h4ck requested changes

2018-01-19 19:24 UTC, G10h4ck commented on retroshare.pri
> +# CONFIG *= retrotor
Could you reformat this in the same way as other compilation options?
The benefit it the other format (like for example retroshare_gui) is that independently from the default value of the option one can either force enable or force disable that option from the qmake invocation without editing the files

2018-01-19 19:24 UTC, G10h4ck commented on retroshare.pri
> +    DEFINES *= RS_ONLYHIDDENNODE
It may be better to just use CONFIG *= rs_onlyhiddennode at this point

2018-02-11 19:49 UTC, merged