Make more APIs jsonapi compatible
RetroShare/RetroShare pull request #1335
Opened 2018-09-08 07:52 UTC by sehraf

Including small  cleanup

2018-09-08 15:52 UTC, sehraf commented
This PR makes my always beloved Lua script obsolete :cry:
[buryTheDead.lua](https://github.com/RetroShare/Lua4RS/blob/master/scripts/buryTheDead.lua) is dead, long live [buryTheDead.py](https://gist.github.com/sehraf/4774b0f45311a2154d1f7f648ddbed6e) 
@HLT

2018-09-08 21:15 UTC, sehraf commented
There goes another Lua script ...
[friendsVersionOverview.lua](https://github.com/RetroShare/Lua4RS/blob/master/scripts/friendsVersionOverview.lua) :arrow_forward: [discOverview.py](https://gist.github.com/sehraf/7bce1eccbb1eee8fa277560522eb2ca1)

2018-09-09 20:11 UTC, G10h4ck requested changes
Great work, just few style observation ;)

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsconfig.h
>  		mRateIn = 0;
This should use proper initializer : mRateIn(0) if initialization is needed

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsconfig.h
> +public:
public can be removed here as it is a struct and averything is public by default

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsconfig.h
> +public:
public can be removed here as it is a struct and averything is public by default

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsdisc.h
> +	virtual ~RsDisc() { return; }
now that you edited the line please take the chance to remove the horrible `return;` on the empty method

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsservicecontrol.h
> +public:
Remove the unneeded `public:` it is a struct so everything is public by default

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsservicecontrol.h
> +public:
Remove the unneeded `public:` it is a struct so everything is public by default

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsservicecontrol.h
> +public:
Remove the unneeded `public:` it is a struct so everything is public by default

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/retroshare/rsservicecontrol.h
> +	virtual ~RsServiceControl() { return; }
now that you edited the line please take the chance to remove the horrible `return;` on the empty method

2018-09-09 20:11 UTC, G10h4ck commented on libretroshare/src/services/p3discovery2.cc
> +	RsStackMutex stack(mDiscMtx); /********** STACK LOCKED MTX ******/
Please use `RS_STACK_MUTEX(mDiscMtx);` without the obvious comment ;)

2018-09-09 20:24 UTC, sehraf commented
done. FYI the `public:` statement is generated by Qt Creator and was just too lazy to remove it all the time :wink:

2018-09-09 22:29 UTC, merged

2018-09-09 22:29 UTC, G10h4ck commented
Thanks for your contribution!