Adding Mac OSX bdboot.txt fixed
RetroShare/RetroShare pull request #1344
Opened 2018-09-15 18:03 UTC by unsenep2pdev

Currently, you have to manually add bdboot.txt into Mac OSX RS Data directory. So by adding this fix will make configuration load automatically every new Identity on Mac OSX Instance.

2018-09-15 20:21 UTC, G10h4ck requested changes
Please remove all those changes that just remove tabs and put spaces, that make reviewing the code more difficult, moreover you should avoid unrelated changes on the same pull request (better open two different pull requests for two different topic).
Altering the indentation using space instead of tab is against our [coding style](https://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style) so please use tab in the lines you edits

2018-09-15 20:21 UTC, G10h4ck commented on libbitdht/src/util/bdthreads.cc
> +    #if __APPLE__
this fi else should be subistituted with `if(mTid)` tha works both on linux and mac without preprocessing

2018-09-15 20:21 UTC, G10h4ck commented on libresapi/src/api/json.cpp
> +#if __APPLE__
this should be moved into `libretroshare/src/util/cxx11retrocompat.h` and then you can add `#include "util/cxx11retrocompat.h"` on this file, anyway RetroShare needs C++11 to compile

2018-09-15 20:21 UTC, G10h4ck commented on libretroshare/src/util/cxx11retrocompat.h
> +    #define GCC_VERSION (__GNUC__*10000+__GNUC_MINOR__*100+__GNUC_PATCHLEVEL__)
`#` must be the first character of the line so the indentation goes after it as it was before, moreover you should use tab instead of space for indentation as described in our [coding style](https://retroshare.readthedocs.io/en/latest/developer/coding/#coding-style)

2018-09-17 05:22 UTC, unsenep2pdev commented on libbitdht/src/util/bdthreads.cc
> +    #if __APPLE__
This recommendation has been fixed and update.

2018-09-17 05:22 UTC, unsenep2pdev commented on libresapi/src/api/json.cpp
> +#if __APPLE__
fixed and update.

2018-09-17 05:22 UTC, unsenep2pdev commented on libretroshare/src/util/cxx11retrocompat.h
> +    #define GCC_VERSION (__GNUC__*10000+__GNUC_MINOR__*100+__GNUC_PATCHLEVEL__)
fixed

2018-09-29 13:53 UTC, PhenomRetroShare commented
Hello,
You need to make a new branch for each PR.

2018-09-29 13:56 UTC, PhenomRetroShare commented on retroshare.pri
> +CONFIG +=rs_autologin
Don't change this.
Only add config when you call qmake, as explained upper.

2019-02-14 01:26 UTC, closed without merging