V0.6.5 forum model2
RetroShare/RetroShare pull request #1415
Opened 2018-11-20 22:29 UTC by csoler

2018-11-21 01:42 UTC, felisucoibi commented
+1000

2018-11-22 22:05 UTC, G10h4ck requested changes

2018-11-22 22:05 UTC, G10h4ck commented on libretroshare/src/retroshare/rsgxsforums.h
> +            std::set<RsGxsMessageId>& msgs_to_request,
please use camel case for param name to be consistent with the other JSON API calls, also in JSON API we can't expose different methods with same name, so this need to have a different name too

2018-11-22 22:05 UTC, G10h4ck commented on retroshare-gui/src/gui/gxsforums/GxsForumThreadWidget.cpp
> +			 * Qt::QueuedConnection is important!
The QueuedConnection part of the comment is not relevant anymore, so it should be removed ;)

2018-11-25 18:07 UTC, G10h4ck commented on retroshare-gui/src/gui/gxsforums/GxsForumThreadWidget.cpp
> +        if(msgs.size() != 1)
This seems an error condition, so a message should be printed ;)

2018-11-27 09:27 UTC, csoler commented
3 things left: sorting (and post pinning), post versions, proper fonts for read/unread to match old system. Apart from that the whole thing seems to work pretty well.

2018-11-28 08:28 UTC, csoler commented
Still stuck with a bug: sorting does not work. Seems to be a GUI problem. When clicking on the header's columns, the Qt sorting method is not called.

2018-12-03 18:52 UTC, felisucoibi commented
testing but seems forums are not loading.

2018-12-03 22:27 UTC, felisucoibi commented
Something is wrong, i know this is not a good way to send you a bug report, but just tell you that rs is crashing, i will try to find where or why but It crashes when entering in forum new posts.

2018-12-07 21:16 UTC, csoler commented
I removed the [WIP] statement because it seems final to me. Please test.

2018-12-09 20:55 UTC, felisucoibi commented
when you choose a forum and no post is selected, before you click in next message and you went to the first last message posted or kind of, now it does nothing, you have to choose a thread first... this feature was usefull to reach fast to new posts. @Cyril

2018-12-09 20:56 UTC, felisucoibi commented
and also the icons are good but maybe they need to be a little more bigger, in a 2K screen are very small, i can't imagine in a 3k monitor.@Cyril

2018-12-09 21:00 UTC, felisucoibi commented
and the most important forums still don't load, forum posts... i can see the thread but when i click in a new post it does not load.

2018-12-15 10:05 UTC, felisucoibi commented
i think more or less is ready for open betateting in master, so we can have a beta widows release and my windows users can test it.

2018-12-16 13:34 UTC, merged