Fix clang warnings
RetroShare/RetroShare pull request #1485
Opened 2019-02-23 23:39 UTC by PhenomRetroShare

All said in commits comment.

2019-02-27 16:04 UTC, G10h4ck requested changes
Seems ok exctept for a missing break; in a switch

2019-02-27 16:04 UTC, G10h4ck commented on retroshare-gui/src/gui/FileTransfer/TransfersDialog.cpp
> +		case TransfersDialog::DownloadTab: ui.tabWidget->setCurrentWidget(ui.tab) ;
`break;` missing, AFAIR if you don't put it following cases are axecuted up to first break, in this case it would jump to `case TransfersDialog::SearchTab:`

2019-03-08 18:04 UTC, PhenomRetroShare commented on retroshare-gui/src/gui/FileTransfer/TransfersDialog.cpp
> +		case TransfersDialog::DownloadTab: ui.tabWidget->setCurrentWidget(ui.tab) ;
Are you sure of that?
https://onlinegdb.com/rJVzA7gDV

2019-04-10 11:30 UTC, PhenomRetroShare commented on retroshare-gui/src/gui/FileTransfer/TransfersDialog.cpp
> +		case TransfersDialog::DownloadTab: ui.tabWidget->setCurrentWidget(ui.tab) ;
Done ;)

2019-04-23 10:35 UTC, G10h4ck approved these changes

2019-04-23 10:41 UTC, G10h4ck approved these changes

2019-04-23 11:26 UTC, merged