Reenable UDP stunner and add documentation
RetroShare/RetroShare pull request #1782
Opened 2020-02-09 11:38 UTC by sehraf

Retroshare implements the STUN protocol (old RFC 3489) to determine the NAT type it is running behind.
While the actual determination logic resides in the class `pqiNetStateBox`, the UDP stunner is responsible for running the actual protocol.

The UDP stunner was disabled a while ago because it seemed only be used to determine the external IP address (using STUN). While this is true as well it's only a byproduct.
As @drbob pointed out it should be re-enabled to allow RS to determine the NAT type again - and based on that knowledge - build more UDP connections (there are multiple types and currently only the one (*direct*) is working).

The patch further adds some (minor) documentation to the UDP stunner, makes the implementation more RFC conform as well as document the RFCs responsible and allows (optionally) to utilize the it for external IP determination. (While this is generally problematical it might be useful for corner cases)

2020-02-09 17:39 UTC, G10h4ck requested changes

2020-02-09 17:39 UTC, G10h4ck commented on libretroshare/src/tcponudp/udpstunner.cc
> +const uint16_t STUN_BINDING_RESPONSE = 0x0101;
Wouldn't it be more appropriate to have those as static constxepr memebers of UdpStunner ?

2020-02-09 17:39 UTC, G10h4ck commented on libretroshare/src/tcponudp/udpstunner.cc
> +	 *	In RFC 3489 [RFC3489], this field was part of
why is RFC3489 repeated twice?

2020-02-09 17:39 UTC, G10h4ck commented on libretroshare/src/tcponudp/udpstunner.cc
> +	((uint32_t *) stun_pkt)[4] = htonl(RsRandom::random_u32());
This 4 lines would e probably easier substituted by a call of `RsRandom::random_bytes`

2020-02-09 17:39 UTC, G10h4ck commented on libretroshare/src/tcponudp/udpstunner.h
>  	struct sockaddr_in remote, eaddr;
Please document both members

2020-02-09 17:42 UTC, sehraf commented on libretroshare/src/tcponudp/udpstunner.cc
> +const uint16_t STUN_BINDING_RESPONSE = 0x0101;
Sure, will do.

2020-02-09 17:42 UTC, sehraf commented on libretroshare/src/tcponudp/udpstunner.cc
> +	 *	In RFC 3489 [RFC3489], this field was part of
It's a plain copy+paste from the RFC.
Can remove the reference in square brackets.

2020-02-09 17:42 UTC, sehraf commented on libretroshare/src/tcponudp/udpstunner.cc
> +	((uint32_t *) stun_pkt)[4] = htonl(RsRandom::random_u32());
Can do

2020-02-09 17:42 UTC, sehraf commented on libretroshare/src/tcponudp/udpstunner.h
>  	struct sockaddr_in remote, eaddr;
Ah, oversaw that! Thanks for the review!

2020-02-09 19:32 UTC, sehraf commented
I've rebased and squashed the fixups.

2020-02-09 23:05 UTC, G10h4ck approved these changes

2020-02-09 23:06 UTC, G10h4ck commented
Now it looks ok to me, I'd wait a few days for @csoler and @drbob to say something, and then merge it

2020-02-12 09:11 UTC, csoler commented
What is the priority of the external IP information using STUN w.r.t. other---more reliable---methods? Normally the expected behavior should be that external IP given by friends (that is 100% reliable) should erase previous estimates given by STUN. Is that the case already?

2020-02-12 11:48 UTC, sehraf commented
When you enable this mechanic (it's off by default) it counts as one (like all other sources, I think)
This happens as soon as **two** dht peers have reported the same external address.

2020-02-12 17:58 UTC, sehraf commented
For the record:
* you must use `CONFIG+=use_dht_stunner_ext_ip` to use the dht stunner as a source of external IP
* dht stunner will only return an external IP when it was reported by two peers
* the switch turns on the old behavior 
* it counts as one like all other sources do, see https://github.com/RetroShare/RetroShare/blob/6f9d875fc69fab52b20e5f886fc614949d937250/libretroshare/src/pqi/p3netmgr.cc#L666

2020-02-15 13:32 UTC, csoler commented
> When you enable this mechanic (it's off by default) it counts as one (like all other sources, I think)
> This happens as soon as **two** dht peers have reported the same external address.
> 
> Edit:
> If desired I can change it to only use it as a fallback.

Well, given that DHT is poisoned by peers who impersnnate your friends with a wrong IP, I am a bit skeptical about the effect on the DHT stunner and the reliability of the IP it will give. So it's important that other more reliable sources (such as discovery) wipe out the result of DHT stunner when you use it.

2020-02-15 16:57 UTC, sehraf commented
I've moved the block that gets the external IP from DHT stunner to the end and added a `if (address_votes.empty()) ` to only use it as fallback when all others haven't provided an IP address.

2020-02-15 21:15 UTC, merged