service descriptions in permission matrix
RetroShare/RetroShare pull request #2021
Opened 2020-06-25 14:28 UTC by RetroPooh

2020-06-29 20:55 UTC, csoler requested changes
Nice contribution. I tried it and noticed that the blox you display is always at the same place and extends far beyond the actual size of the text. This is the opposite of how the text for switches displays: it fits the text and shows up next to the mouse. If possible, could you stick to that display style? There's also one small issue in the code (see comments).

2020-06-29 20:55 UTC, csoler commented on retroshare-gui/src/gui/settings/RSPermissionMatrixWidget.cpp
> +				uint16_t serviceOrig = (uint16_t)((service_ids[i] - (((uint32_t)RS_PKT_VERSION_SERVICE) << 24) ) >> 8);
not so nice. Normally it's better to do serviceOrig=(service_ids[i]>>8) & 0xffff; It avoids substracting uint32_t values.

2020-06-30 08:56 UTC, RetroPooh commented on retroshare-gui/src/gui/settings/RSPermissionMatrixWidget.cpp
> +				uint16_t serviceOrig = (uint16_t)((service_ids[i] - (((uint32_t)RS_PKT_VERSION_SERVICE) << 24) ) >> 8);
ok, your formula works, but why are we ok with dropping RS_PKT_VERSION_SERVICE ?

2020-06-30 09:59 UTC, csoler commented on retroshare-gui/src/gui/settings/RSPermissionMatrixWidget.cpp
> +				uint16_t serviceOrig = (uint16_t)((service_ids[i] - (((uint32_t)RS_PKT_VERSION_SERVICE) << 24) ) >> 8);
RS_PKT_VERSION_SERVICE is just a tag at the start of the RsItem ID. It should be discarded to leave the service ID.

2020-06-30 10:44 UTC, sehraf commented
This would not have happened with dedicated types and functions for converting :wink:

2020-06-30 10:44 UTC, sehraf commented on retroshare-gui/src/gui/settings/RSPermissionMatrixWidget.cpp
> +				uint16_t serviceOrig = (uint16_t)((service_ids[i] - (((uint32_t)RS_PKT_VERSION_SERVICE) << 24) ) >> 8);
This would not have happened with dedicated types and functions for converting :wink:

2020-09-11 20:29 UTC, csoler commented
thx! Looks very nice.

2020-09-11 20:29 UTC, merged