V0.6 pgp handler
RetroShare/RetroShare pull request #2450
Opened 2021-08-15 08:46 UTC by csoler

Turns PGPHandler into an abstract class that is derived as OpenPGPSDKHandler to provide a specific implementation for openpgpsdk. This should make it easier to switch to any other PGP package. Also got rid of getAuthGPG(), using static members for AuthGPG instead.

2021-10-28 07:33 UTC, G10h4ck requested changes

2021-10-28 07:33 UTC, G10h4ck commented on libretroshare/src/gossipdiscovery/p3gossipdiscovery.cc
> +        if (!(AuthGPG::isGPGAccepted(pgpId)))
Now that you are refactoring this please rename `isGPGAccepted` into `isPgpAccepted` note the letters changed not just the casing ;)

2021-10-28 07:33 UTC, G10h4ck commented on libretroshare/src/pgp/pgphandler.cc
> +		std::cerr << "\tName          : " <<  it->second._name << std::endl;
Isn't better to use `RS_DBG() <<` and friends here so it works also on android without black magic?

2021-10-28 07:36 UTC, G10h4ck commented
Beside the inline comments, shouldn't we use a global pointer + methods like we do for most services like `rsFiles->someMethod()` this way we can easily expose the functionality also to JSON API, moreover i think it is easier to integrate other PGP implementations that way instead of static methods, as another implementation may need to keep some runtime state which is more difficult to do within static stuff.

2021-10-28 07:41 UTC, csoler commented
I actually hesitated between the two options. This one has some advantages as well, but otherwise the pointer method would be more consistent with the rest of the code.

2021-10-28 07:50 UTC, G10h4ck commented
I agree on keeping it homogeneous with the rest of the code, so please switch to global pointer + methods style now that your are still in time ;)
When I started coding into RS having so different patterns and anti-patterns into different parts of code added much to the entry barrier.

2021-10-29 17:02 UTC, csoler commented on libretroshare/src/gossipdiscovery/p3gossipdiscovery.cc
> +        if (!(AuthGPG::isGPGAccepted(pgpId)))
done

2021-10-29 17:07 UTC, csoler commented
Well actually looking at the code AuthPGP is not a structure that we may expose at the API level. So there's no problem making it static.

2021-12-13 17:56 UTC, G10h4ck commented on libretroshare/src/pgp/pgphandler.cc
> +		std::cerr << "\tName          : " <<  it->second._name << std::endl;
ping

2021-12-13 20:20 UTC, csoler commented
ok I fixed both conflicts and std::cerr problems.

2021-12-18 14:30 UTC, merged